name = "mediumbackend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMjY2ZWU4NDctYmVlNC00YWQ2LWIxMDQtNzAwNGI3MmI4ODMwIiwidGVuYW50X2lkIjoiNTQ4YjA0MmNkY2NlYTQyZTY5ZjY0OWZkNjM2ZmZhYjVkMmNkZmZiYjg2MTE2Mzc5ZDM0NzYzOGFhMmUyODM0YiIsImludGVybmFsX3NlY3JldCI6ImZjODYwMDNiLTFjZjEtNDMwOC1hZGMwLTIwZTgxMjU2M2I3NSJ9.ykqmN_8xNDrGP8tPkSkz8vnu3AVv20h7uLdmQaA7-Eg"

JWT_SECRET = "asdasdasd"
